name: CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.0'

    - name: Run vet
      run: go vet ./cmd/webserver

    - name: Run build
      run: go build ./cmd/webserver

    - name: Run tests
      env:
        GHO_CLIENT_ID: ${{secrets.GHO_CLIENT_ID}}
        GHO_CLIENT_SECRET: ${{secrets.GHO_CLIENT_SECRET}}
      run: go test ./pkg/webserver -v
